"""new updates

Revision ID: 2d2147f149f0
Revises: 4294962178ac
Create Date: 2026-03-16 00:10:39.802161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d2147f149f0'
down_revision: Union[str, Sequence[str], None] = '4294962178ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audiogram_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ear_id', sa.Integer(), nullable=False),
    sa.Column('test_type', sa.Enum('AC', 'AC_MASKED', 'BC', 'BC_MASKED', name='testtypeenum'), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('threshold_db', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ear_id'], ['ears.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ear_id', 'test_type', 'frequency', name='uq_points_ear_test_freq')
    )
    op.create_index(op.f('ix_audiogram_points_id'), 'audiogram_points', ['id'], unique=False)
    op.drop_index(op.f('ix_bc_thresholds_id'), table_name='bc_thresholds')
    op.drop_table('bc_thresholds')
    op.drop_index(op.f('ix_ac_thresholds_id'), table_name='ac_thresholds')
    op.drop_table('ac_thresholds')
    op.add_column('attempts', sa.Column('masking_level_db', sa.Float(), nullable=True))
    op.create_unique_constraint('uq_ears_patient_side', 'ears', ['patient_id', 'side'])
    op.add_column('patients', sa.Column('source_type', sa.Enum('REAL', 'SYNTHETIC', name='patientsourceenum'), nullable=False))
    op.add_column('stored_thresholds', sa.Column('is_final', sa.Boolean(), nullable=False))
    op.drop_constraint(op.f('stored_thresholds_attempt_id_fkey'), 'stored_thresholds', type_='foreignkey')
    op.create_foreign_key(None, 'stored_thresholds', 'attempts', ['attempt_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stored_thresholds', type_='foreignkey')
    op.create_foreign_key(op.f('stored_thresholds_attempt_id_fkey'), 'stored_thresholds', 'attempts', ['attempt_id'], ['id'])
    op.drop_column('stored_thresholds', 'is_final')
    op.drop_column('patients', 'source_type')
    op.drop_constraint('uq_ears_patient_side', 'ears', type_='unique')
    op.drop_column('attempts', 'masking_level_db')
    op.create_table('ac_thresholds',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ear_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('test_type', postgresql.ENUM('AC', 'AC_MASKED', 'BC', 'BC_MASKED', name='testtypeenum'), autoincrement=False, nullable=False),
    sa.Column('hz_250', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('hz_500', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('hz_750', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('hz_1000', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('hz_1500', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('hz_2000', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('hz_3000', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('hz_4000', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('hz_6000', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('hz_8000', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ear_id'], ['ears.id'], name=op.f('ac_thresholds_ear_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ac_thresholds_pkey'))
    )
    op.create_index(op.f('ix_ac_thresholds_id'), 'ac_thresholds', ['id'], unique=False)
    op.create_table('bc_thresholds',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ear_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('test_type', postgresql.ENUM('AC', 'AC_MASKED', 'BC', 'BC_MASKED', name='testtypeenum'), autoincrement=False, nullable=False),
    sa.Column('hz_500', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('hz_750', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('hz_1000', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('hz_1500', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('hz_2000', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('hz_3000', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('hz_4000', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ear_id'], ['ears.id'], name=op.f('bc_thresholds_ear_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('bc_thresholds_pkey'))
    )
    op.create_index(op.f('ix_bc_thresholds_id'), 'bc_thresholds', ['id'], unique=False)
    op.drop_index(op.f('ix_audiogram_points_id'), table_name='audiogram_points')
    op.drop_table('audiogram_points')
    # ### end Alembic commands ###
