"""update_patinet_and_session_model

Revision ID: 4294962178ac
Revises: 79a4215735e5
Create Date: 2026-03-13 23:32:47.740812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4294962178ac'
down_revision: Union[str, Sequence[str], None] = '79a4215735e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('patients_session_id_key'), 'patients', type_='unique')
    op.drop_constraint(op.f('patients_session_id_fkey'), 'patients', type_='foreignkey')
    op.drop_column('patients', 'session_id')
    op.add_column('sessions', sa.Column('patient_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'sessions', ['patient_id'])
    op.create_foreign_key(None, 'sessions', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_constraint(None, 'sessions', type_='unique')
    op.drop_column('sessions', 'patient_id')
    op.add_column('patients', sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('patients_session_id_fkey'), 'patients', 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('patients_session_id_key'), 'patients', ['session_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
