"""initial migration

Revision ID: 79a4215735e5
Revises: 
Create Date: 2026-03-11 05:00:02.182581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79a4215735e5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('ear_side', sa.Enum('LEFT', 'RIGHT', name='earsideenum'), nullable=False),
    sa.Column('test_type', sa.Enum('AC', 'AC_MASKED', 'BC', 'BC_MASKED', name='testtypeenum'), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('intensity', sa.Float(), nullable=False),
    sa.Column('response', sa.Enum('HEARD', 'NOT_HEARD', name='responseenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attempts_id'), 'attempts', ['id'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_table('ears',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.Enum('LEFT', 'RIGHT', name='earsideenum'), nullable=False),
    sa.Column('hearing_type', sa.Enum('NORMAL', 'CONDUCTIVE', 'SENSORINEURAL', 'MIXED', name='hearingtypeenum'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ears_id'), 'ears', ['id'], unique=False)
    op.create_table('stored_thresholds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('ear_side', sa.Enum('LEFT', 'RIGHT', name='earsideenum'), nullable=False),
    sa.Column('test_type', sa.Enum('AC', 'AC_MASKED', 'BC', 'BC_MASKED', name='testtypeenum'), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('threshold_db', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stored_thresholds_id'), 'stored_thresholds', ['id'], unique=False)
    op.create_table('ac_thresholds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ear_id', sa.Integer(), nullable=False),
    sa.Column('test_type', sa.Enum('AC', 'AC_MASKED', 'BC', 'BC_MASKED', name='testtypeenum'), nullable=False),
    sa.Column('hz_250', sa.Float(), nullable=False),
    sa.Column('hz_500', sa.Float(), nullable=False),
    sa.Column('hz_750', sa.Float(), nullable=False),
    sa.Column('hz_1000', sa.Float(), nullable=False),
    sa.Column('hz_1500', sa.Float(), nullable=False),
    sa.Column('hz_2000', sa.Float(), nullable=False),
    sa.Column('hz_3000', sa.Float(), nullable=False),
    sa.Column('hz_4000', sa.Float(), nullable=False),
    sa.Column('hz_6000', sa.Float(), nullable=False),
    sa.Column('hz_8000', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ear_id'], ['ears.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ac_thresholds_id'), 'ac_thresholds', ['id'], unique=False)
    op.create_table('bc_thresholds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ear_id', sa.Integer(), nullable=False),
    sa.Column('test_type', sa.Enum('AC', 'AC_MASKED', 'BC', 'BC_MASKED', name='testtypeenum'), nullable=False),
    sa.Column('hz_500', sa.Float(), nullable=False),
    sa.Column('hz_750', sa.Float(), nullable=False),
    sa.Column('hz_1000', sa.Float(), nullable=False),
    sa.Column('hz_1500', sa.Float(), nullable=False),
    sa.Column('hz_2000', sa.Float(), nullable=False),
    sa.Column('hz_3000', sa.Float(), nullable=False),
    sa.Column('hz_4000', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ear_id'], ['ears.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bc_thresholds_id'), 'bc_thresholds', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bc_thresholds_id'), table_name='bc_thresholds')
    op.drop_table('bc_thresholds')
    op.drop_index(op.f('ix_ac_thresholds_id'), table_name='ac_thresholds')
    op.drop_table('ac_thresholds')
    op.drop_index(op.f('ix_stored_thresholds_id'), table_name='stored_thresholds')
    op.drop_table('stored_thresholds')
    op.drop_index(op.f('ix_ears_id'), table_name='ears')
    op.drop_table('ears')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_attempts_id'), table_name='attempts')
    op.drop_table('attempts')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
